- source/fb_nextgen_mmm_v20.0.exec.R
- source/fb_nextgen_mmm_v20.0.func.R
- source/fb_nextgen_mmm_v20.0.plot.R
{\rtf1\ansi\ansicpg1252\cocoartf1671\cocoasubrtf600
{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red42\green44\blue51;\red249\green249\blue249;\red42\green44\blue51;
\red249\green249\blue249;}
{\*\expandedcolortbl;;\cssrgb\c21961\c22745\c25882;\cssrgb\c98039\c98039\c98039;\cssrgb\c21961\c22745\c25882;
\cssrgb\c98039\c98039\c98039;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl340\partightenfactor0
\f0\fs30 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 # Contributing to FB Robyn MMM R script\
* Bug fix (non-breaking change which fixes an issue)
* New feature …
> Gufeng's branch - Nevergrad integration

- source/fb_robyn.exec.R
- source/fb_robyn.func.R
Please include a summary of the change and which issue is fixed. Please also
include relevant motivation and context.
- Breaking change (fix or feature that would cause existing functionality to not
work as expected)
- API change with a documentation update
- Additional test coverage
- Code cleanup or just keeping up with the latest Rustc nightly
Checklist:
> add libraries and avoid dt setnames error

- docs/docusaurus.config.js
> website: fix config URL

- docs/docusaurus.config.js
Reverts facebookexperimental/Robyn#45
> Revert "website: fix config URL"

- source/fb_robyn.exec.R
- source/fb_robyn.func.R
- source/fb_robyn.optm.R
- deprecated set_modTrainSize to prepare for rolling window feature
- remove rsq_test and show rsq_train instead --> overfitting is mitigated by ridge regression
- fix data.table order bug
> Deprecated time series train test validation

- source/fb_robyn.func.R
- source/fb_robyn.optm.R
- fix data.table ordering issues by using [order(rank(...))] for string variables
- change wording spend-reach to spend exposure
- add date sorting to input data to prevent not asending dates causing issues
> fix further data.table ordering issues

- source/fb_robyn.func.R
- In actual & fitted line chart and the residual vs. fitted diagnostic chart, the bug of missing intercept in the decomp is fixed
- adapt the spend exposure plot scale to number of channels
> fix decomp visualisation bug

- source/fb_robyn.func.R
- website/yarn.lock
Before this improvement, each time restarting a modeling session a second time, the R session crashed because the parallelization was not correctly closed.
These changes therefore give :
- The ability to launch several modelizations in a row without crashing R session.
- The possibility of looping on several models at once and correctly close our parallelizations after modeling
> Improved f.robyn.func.R (R session aborted fixed bug )

- source/fb_robyn.func.R
Reverts facebookexperimental/Robyn#106
> Revert "Improved f.robyn.func.R (R session aborted fixed bug )"

- util/robyn.py
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- API change with a documentation update
- Additional test coverage
- Code cleanup or just keeping up with the latest Rustc nightly
Checklist:
> Fix jde 20211209

- util/debug.py
- util/demo.py
- util/robyn.py
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- API change with a documentation update
- Additional test coverage
- Code cleanup or just keeping up with the latest Rustc nightly
Checklist:
> Updated for fix object to work. Updating check conditions to work

- R/DESCRIPTION
- R/R/model.R
- R/R/refresh.R
- R/man/robyn_mmm.Rd
- R/man/robyn_run.Rd
Feat: a new parameter to enable users to customize `glmnet`'s behavior negative intercepts.
Solves #256
> feat: enable new intercept_sign param #256

- .idea/workspace.xml
> Updated with master branch.  Created new Robyn file

- R/R/clusters.R
Hi,
I tried to understand how Robyn selects best model inside a cluster.
I've found some parts which could be fixed/improved - see below. 
Sorry in advance if I didn't understand the initial idea.
1. ```.clusters_df()``` in clusters.R sometimes returns ```Inf```
It happens as a result of dividing by zero which is unavoidable because of normalization in ```.min_max_norm()```
See screenshot of ```df``` and ```crit_df``` values inside ```.clusters_df()```:
2. These Inf values seem to be breaking error value calculation:
In general model with nrmse=8.19 (normalized and weighted) cannot have error=0, in my opinion it doesn't make sense
I prepared a fix with following changes:
- switch weight formula from ```balance[1] / .data$nrmse``` to ```.data$nrmse / balance[1]``` to avoid ```Inf``` values …
> Clusters: potential improvement in Top Solution selection

- website/docs/releases.mdx
Docs: updating website to include 3.10.0 release
> Docs: updating website to include 3.10.0 release

- website/docs/releases.mdx
Docs: updated website releases to include v3.10.1
> Docs: updated website releases to include v3.10.1

- R/R/model.R
> feat: always constraint prophet coefs to 0-1

- R/R/clusters.R
- R/R/convergence.R
- R/R/inputs.R
- R/R/plots.R
- R/R/response.R
- R/R/transformation.R
- fix: Bug fix (non-breaking change which fixes an issue)
- feat: New feature (non-breaking change which adds functionality)
- docs: API change with a documentation update
- test: Additional test coverage
- reformat: Code cleanup, recoding or reformating code
- Fork the repo and create your branch from master (latest dev version).
- If you've changed docuemntation, run `devtools::document()`. Should update .Rd files.
- Ensure all tests pass, run `devtools::check()`. Should have no notes, no warning, no errors.
> Fix plotting issues

- R/DESCRIPTION
- R/R/checks.R
- R/R/clusters.R
- R/R/inputs.R
- R/R/pareto.R
- R/man/robyn_clusters.Rd
> fix: mediaVecCollect's organic vars weren't being multiplied by coef values + InputCollect print when no prophet country set

- R/DESCRIPTION
- R/R/plots.R
Checking with CRAN if this one can land ASAP.
> fix: one-pager decomp labels and warning

- robyn_api/python_helper.py
- robyn_api/robynapi_enpoints.R
- Added the robyn_refresh endpoint in robynapi_endpoint.R.
- Added an example to call robyn_refresh in robyn_python_notebook.ipynb.
- Updated write_robynmodel() in python_helper.py to default to outputting JSON to plot_folder if no path is specified.
- Modified variable names.
- fix: Bug fix (non-breaking change which fixes an issue)
- feat: New feature (non-breaking change which adds functionality)
- docs: API change with a documentation update
- test: Additional test coverage
- reformat: Code cleanup, recoding or reformating code
- Fork the repo and create your branch from master (latest dev version).
- If you've changed docuemntation, run …
> Added robyn_refresh endpoint

- R/DESCRIPTION
- R/R/allocator.R
- R/man/robyn_allocator.Rd
Based on use-case shared by @yu-ya-tanaka
> feat: new keep_zero_coefs param in robyn_allocator()

- python/src/robyn/modeling/base_model_executor.py
- python/src/robyn/modeling/entities/enums.py
- python/src/robyn/modeling/entities/modeloutputs.py
- python/src/robyn/modeling/entities/modelrun_trials_config.py
- python/src/robyn/modeling/model_executor.py
- python/src/robyn/modeling/ridge_model_builder.py
**Summary:** We are including the interfaces (methods and data classes) for the modeling subcomponent in Python. This interface is inferred from model.R.  
- feat: New Python interfaces for modeling subcomponent. 
```mermaid
classDiagram
class BaseModelExecutor {
<<abstract>>
+MMMData mmmdata
+HolidaysData holidays_data
+Hyperparameters hyperparameters
+CalibrationInput calibration_input
+FeaturizedMMMData featurized_mmm_data
+model_run(dt_hyper_fixed: Dict, ts_validation: bool, add_penalty_factor: bool, refresh: bool, seed: int, cores: int, trials_config: TrialsConfig, rssd_zero_penalty: bool, objective_weights: Dict, nevergrad_algo: NevergradAlgorithm, intercept: bool, intercept_sign: str, outputs: bool, model_name: Models)* ModelOutputs
}
class ModelExecutor { …
```
> [interfaces] add modeling from robynpy_interfaces

- python/src/robyn/modeling/transformations/transformations.py
- python/src/robyn/visualization/transformation_visualization.py
**Depends on https://github.com/facebookexperimental/Robyn/pull/1050**
**Summary:** We are including the interfaces (methods and data classes) for the transformation subcomponent in Python. This interface is inferred from transformations.R.  
- feat: New Python interfaces for transformation subcomponent. 
```mermaid
classDiagram
class Transformation {
-mmm_data: MMMData
-media_channels: list
-channel_data: Dict[str, np.ndarray]
+__init__(mmm_data: MMMData)
-_get_media_channels() list
-_get_channel_data() Dict[str, np.ndarray]
+michaelis_menten(channel: str, vmax: float, km: float, reverse: bool) np.ndarray
+adstock_geometric(channel: str, theta: float) Dict[str, Union[np.ndarray, float]]
+adstock_weibull(channel: str, shape: float, scale: float, window_length: int, adstock_type: str) …
```
> [interfaces] add transformation Python interfaces

- python/src/robyn/data/entities/hyperparameters.py
- python/src/robyn/data/validation/hyperparameter_validation.py
- python/src/robyn/robyn.py
- python/tests/test_hyperparameter_validation.py
This PR implements the `HyperparametersValidation` class in Python, adapting the functionality from the R `check_hyperparameters` function and related functions. The new implementation provides a more structured and object-oriented approach to validating hyperparameters in the Python version of Robyn.
Fixes # (issue number related to hyperparameter validation in Python)
- feat: New feature (non-breaking change which adds functionality)
- test: Additional test coverage
1. Implemented `HyperparametersValidation` class in `hyperparameter_validation.py`.
2. Adapted `check_hyperparameters`, `check_train_size`, `check_hyper_limits`, and `hyper_names` functions from R to Python.
3. Updated the `Hyperparameters` and `ChannelHyperparameters` classes to better support validation.
4. Added …
> Implementing hyperparameter_validation.py

- .github/workflows/python-app.yml
- python/pyproject.toml
- python/src/robyn/modeling/feature_engineering.py
- python/tests/modeling/test_feature_engineering.py
Added unit tests for feature engineering.
Feature engineering code coverage is 74% with tests added in this PR
> Adding feature engineering unit test cases

- python/src/robyn/modeling/convergence/convergence.py
Generated logging with prompt below.
Task Description
- Take the provided Python code and enhance with comprehensive logging capabilities. The logging should include:
DEBUG level logs:
- log data entities being processed.
- Track progress through critical sections of the code.
INFO level logs:
- Highlight high-level progress milestones.
WARNING and ERROR level logs:
- Capture detailed error messages for troubleshooting.
Instructions
- Focus solely on the xyz method within the provided code.
- Introduce logging statements to meet the specified requirements.
- Deduplicate any redundant log statements to maintain code efficiency.
- Do not alter the existing implementation or logic.
- Remove or replace print statements with log statements
- Add any private methods needed to make objects …
> AI Generated logging.

- python/src/robyn/visualization/pareto_visualizer.py
**Note**: Plotting is done with 90% accuracy expectation. Once all the 8 plots are generated and merged, a different PR will be raised if needed to take care of accuracy.
Add diagnostic plot for fitted vs residual analysis
Implements scatter plot of fitted values vs residuals
Adds LOWESS smoothing with confidence bands
Includes horizontal reference line
Matches R implementation styling
Uses consistent value formatting
Supports both standalone and subplot integration
Testing:
Graph plotted by R:
> Robyn one pager: generate_diagnostic_plot implementation

- python/src/robyn/common/common_util.py
- python/src/robyn/modeling/model_executor.py
- python/src/robyn/modeling/ridge_model_builder.py
Added CommonUtils with get_cores_available method and updated code to use it.
> Cores update

- python/src/robyn/allocator/allocation_optimizer.py
- python/src/robyn/allocator/budget_allocator.py
- python/src/robyn/allocator/entities/allocation_config.py
- python/src/robyn/allocator/entities/allocation_constraints.py
- python/src/robyn/allocator/entities/allocation_results.py
- python/src/robyn/allocator/entities/enums.py
- python/src/robyn/allocator/media_response.py
- python/src/robyn/allocator/response_calculator.py
- python/src/robyn/calibration/media_effect_calibration.py
- python/src/robyn/calibration/media_transformation.py
- python/src/robyn/common/config/logging.conf
- python/src/robyn/data/entities/mmmdata.py
- python/src/robyn/data/validation/calibration_input_validation.py
- python/src/robyn/data/validation/holidays_data_validation.py
- python/src/robyn/data/validation/hyperparameter_validation.py
- python/src/robyn/data/validation/mmmdata_validation.py
- python/src/robyn/modeling/base_model_executor.py
- python/src/robyn/modeling/clustering/cluster_builder.py
- python/src/robyn/modeling/clustering/clustering_config.py
- python/src/robyn/modeling/feature_engineering.py
- python/src/robyn/modeling/model_executor.py
- python/src/robyn/modeling/pareto/hill_calculator.py
- python/src/robyn/modeling/pareto/response_curve.py
- python/src/robyn/modeling/transformations/transformations.py
[robynpy_2024-11-10_20-42-23.log](https://github.com/user-attachments/files/17695249/robynpy_2024-11-10_20-42-23.log) 
Generated logging for individual file with following prompt. See attached debug logs from tutorial1.ipnyb
Task Description 
- Take the provided code and enhance it with comprehensive logging capabilities. 
The logging should include: 
DEBUG level logs: - Print data entities being processed. 
- Track progress through critical sections of the code. INFO level logs: - Highlight high-level progress milestones. 
WARNING and ERROR level logs: 
- Capture detailed error messages for troubleshooting. 
Instructions 
- Focus solely on the requested module/file/method within the provided code. 
- Introduce logging statements to meet the specified requirements. 
- Deduplicate any …
> Logging - Adding log statements for most of the python source code

- python/src/robyn/reporting/onepager_reporting.py
Add OnePagerReporter class for MMM visualization dashboard
- Implements automated generation of 8 key MMM visualizations in a single dashboard
- Includes model performance metrics (R², NRMSE, DECOMP.RSSD, MAPE)
- Supports customizable plot selection and grid layout
- Handles visualization of Pareto fronts, clustering results, response curves
- Implements error handling and safe metric formatting
- Uses consistent styling with seaborn and matplotlib configurations
Testing:
Graphs plotted by R code:
> Robyn one pager: reporter initializing viz and calling plot functions.

- python/src/robyn/reporting/onepager_reporting.py
- python/src/robyn/visualization/cluster_visualizer.py
- python/src/robyn/visualization/pareto_visualizer.py
- python/src/robyn/visualization/response_visualizer.py
- python/src/robyn/visualization/transformation_visualizer.py
Add OnePagerReporter class with visualization capabilities
- Implement OnePagerReporter for generating MMM one-page reports
- Support generating reports for single and multiple solution IDs
- Add support for clustered solution visualization
- Add support for Pareto solution visualization
- Configurable plot layout with 8 standard graphs:
* Spend effect & performance
* Response decomposition waterfall
* Actual vs predicted response
* Diagnostic plots
* Immediate vs carryover effects
* Adstock rate analysis
* Bootstrap confidence intervals
* Response curves
- Implement flexible grid layout system
- Add error handling and logging
- Add configurable save options with DPI control
- Add input validation and type checking
Individual visualizer changes:
Updated each visualizer to plot the graphs …
> one pager end to end integration.

- python/src/robyn/data/entities/enums.py
- python/src/robyn/reporting/onepager_reporting.py
Enhance OnePagerReporter with PlotType enum and validation
Add type safety and validation to plot selection in OnePagerReporter through 
a new PlotType enum class. This change enforces strict validation of plot 
types and provides better error handling.
Key Changes:
- Create PlotType enum to define valid plot types
- Add validation for plot type inputs
- Update generate_one_pager to enforce enum validation
- Add helpful error messages for invalid plot types
- Fix title overlapping issue in plot layout
- Limit number of Pareto solutions to 5 when top_pareto is True
Technical Details:
- Add PlotType.validate_plot_types() method for input validation
- Update plot_config to use enum values as keys
- Adjust layout spacing to prevent title overlap
- Add MAX_SOLUTIONS constant (5) for Pareto …
> Enhance OnePagerReporter with PlotType enum and validation

- python/src/robyn/robyn.py
Refactored robyn.py to have consistency in the way visualizer is used.
NOTE: this will break tutorial1. Subsequent PR will fix it.
> Refactored robyn.py

- python/src/robyn/visualization/feature_visualization.py
> Fix spend exposure graph twice

- python/src/robyn/modeling/pareto/data_aggregator.py
- python/src/robyn/modeling/pareto/pareto_optimizer.py
- python/src/robyn/modeling/pareto/plot_data_generator.py
- python/src/robyn/modeling/pareto/response_curve.py
- python/tests/modeling/pareto/test_response_curve.py
Refactored Pareto_optimizer logic to other classes and made things more modular.
The functionality and outputs still remain the same as before just cleaner code to follow
One pager after refactor:
One pager from Robyn_notebook:
> refactored pareto_optimizer code

- python/src/robyn/reporting/onepager_reporting.py
> Change the order of one pager plots

- python/pyproject.toml
Bumping up robynpy PyPi package release version to 0.1.1
> Bumping up python release to 0.1.1

- python/src/robyn/modeling/ridge/ridge_metrics_calculator.py
Summary
This PR optimizes _calculate_decomp_spend_dist and _calculate_x_decomp_agg, reducing redundant computations and improving overall model execution time by ~23% on python version.
This PR does not address a specific GitHub issue but significantly enhances efficiency.
fix: Performance optimization (non-breaking change that improves efficiency)
Decomposition calculations were a major performance bottleneck, slowing down overall execution.
Precomputed denominator for xDecompMeanNon0Perc, eliminating redundant computations inside loops.
Before Optimization:
_calculate_decomp_spend_dist: 116.5s
_calculate_x_decomp_agg: 318.1s
_run_nevergrad_optimization: 1304s
After Optimization:
_calculate_decomp_spend_dist: 72.43s (~38% faster)
_calculate_x_decomp_agg: 67.4s (~78% faster) …
> Optimize decomposition calculations to reduce model train time by ~23% (Python version)

- python/README.md
- python/pyproject.toml
- python/requirements.txt
- As titled. Updated duplicated pypi dependencies. Updated README.
> remove dup pypi deps
