facebookexperimental/Robyn

- source/fb_robyn.func.R
fixing nlsLM fitting
Fixes #27  (issue)
- Bug fix
> spend reach MM nls fix

- source/fb_robyn.func.R
> remove coef0==FALSE to avoid "Plotting 0 pareto optimum models"

- source/fb_robyn.exec.R
- source/fb_robyn.func.R
- source/fb_robyn.optm.R
- add condition check: warning when training data only contains 0
- change spend share logic: mean spend share with non-zero periods is implemented instead of total spend share: more realistic spend scenario. This adaption has impact on decomp.rssd as well as budget allocator
- fix MM nls reverse issue at plotting
> Dealt with new media channels with many 0

- source/fb_robyn.func.R
The ​​parameters values in the Michaelis-Menten model formula have been inverted.
Michaelis-Menten model formula :
Michaelis-Menten model parameters :
+ **Vmax** -> represents the maximum velocity achieved by the system, at maximum (saturating) substrate concentrations.
+ **KM**(the Michaelis constant) -> is the substrate concentration at which the reaction velocity is 50% of the Vmax.
+ Corrected the Michaelis-Menten model formula
+ Changes the NLS Start Values
> Correction of the Michaelis-Menten model formula

- .Rbuildignore
No need to import `docs` directory on package builds. We also have to fix dependencies on `DESCRIPTION` file (something like [this](https://github.com/laresbernardo/Robyn/blob/master/DESCRIPTION))
> Remove docs from build

- R/R/inputs.R
- R/R/model.R
Our team found following error message if we run RobynMMM without organic vars (empty vector in parameters)
Error message:
```
>>> Plotting 17 Pareto optimum models...
|====
Error in `[.data.table`(dt_transformSpend, , `:=`((InputCollect$organic_vars),  (run_robyn_mmm.R#209): LHS of := isn't column names ('character') or positions ('integer' or 'numeric')
```
Fix is quite simple - please review it.
The change has been tested on real production data.
> Fix error message when no organic vars were provided

- R/DESCRIPTION
- R/R/inputs.R
- R/man/prophet_decomp.Rd
- Enabled user to be able to change default prophet parameters, especially `yearly.seasonality` and `weekly.seasonality`
- Fix #262
> feat: enable users to change default prophet inputs #262

- R/R/model.R
- R/R/pareto.R
Fix a bug where we were taking the rolling window length for weibull adstocks twice resulting in NA values breaking the model process. relevant issue - https://github.com/facebookexperimental/Robyn/issues/353
bug-fix
used demo.R to test functionality of all functions with both weibull adstocks
> Weibull testfix

- R/R/inputs.R
When I submit custom Prophet parameters to robyn_input() as shown below:
```R
InputCollect <- robyn_inputs(
...
, seasonality.mode = "multiplicative"
...
)
```
**Actual result** 
I see following log message without any custom parameters: 
`Using custom prophet parameters:`
**Expected result**  
`Using custom prophet parameters: seasonality.mode`
Pls review this tiny fix for the log message.
I run fixed version of Robyn as part of our internal project - everything works fine, log message looks as it should be.
No other issues observed.
> Fix log message "Using custom prophet parameters"

- website/docusaurus.config.js
Page edit links on the website are currently broken, e.g. this one from the [Quick Start page](https://facebookexperimental.github.io/Robyn/docs/quick-start/): https://github.com/facebookexperimental/Robyn/docs/quick-start.mdx
Change the Docusaurus `editUrl` to make the edit links work. With this change, the above example link would change to: https://github.com/facebookexperimental/Robyn/edit/main/website/docs/quick-start.mdx
"The final URL is computed by `editUrl + relativeDocPath`."
– https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#editUrl
> Make website page edit links work

- R/R/refresh.R
- R/man/robyn_refresh.Rd
Currently the refresh() function selects the refresh version on its own. Here I added an additional bool param version_prompt that allows to pause the code and ask the user to input a specific refresh model name.
- Locally on personal machine using custom dataset
Checklist:
> Added version_prompt parameter to robyn_refresh()

- R/R/model.R
During debug of calibration MAPE calculation function I've found a small bug in calibration_input channel names matching.
It could cause wrong MAPE calculation in rare cases. Pls see the example and fix below:
```
getLiftMedia[m]<- c('google')
calibration_input$channel <- c('facebook', 'google', 'google_organic')
liftWhich <- str_which(calibration_input$channel, getLiftMedia[m])
liftWhich <- which(calibration_input$channel == getLiftMedia[m])
```
Tested on our internal Robyn-based project.
> Fix channel names matching in calibrate_mmm()

- R/R/transformation.R
I tried to recreate the computation of the Hill saturation function, and found that Robyn's code for it seemed unnecessarily convoluted and wasteful.
Why is `range(x)` computed twice? (Maybe the R compiler is smart enough to just do it once anyway?)
Why create a linear sequence (and why with 100 steps in particular?) when it is immediately reduced to a scalar with `quantile`?
Why round the result at all, and why round to four decimals in particular?
I think all these things are unnecessary, and rewrote the computation to use a simple linear interpolation instead. I also renamed the variable to reflect it's content.
- Code cleanup
By logical reasoning and by manual comparison of the original and proposed computations on the same test data.
> refactor: modify inflexion computation for precision and simplicity

- R/R/checks.R
- R/man/robyn_response.Rd
update robyn_response() to receive numeric vector.
current robyn_response allow to receive numeric value. If we want to get multiple result we needed to run multiple times or loop it. It takes so much time to try it. By allowing numeric vector it will reduce time of getting outputs.
Unit test of robyn_response().
Tested 
- to allow numeric value and vectors.
- send error if it is not numeric vector.
- send error if it has negative value.
Checklist:
> update robyn_response() to receive numeric vector

- website/docs/releases.mdx
Docs: updated v3.9.0 to releases
Tested by markdown renderer
> Docs: updated v3.9.0 to releases

- R/R/outputs.R
- R/R/plots.R
When enabling ts_validation for OutputModels, robyn_outputs did not output the one-pager plots in the plot folder. This happened because OutputCollect$OutputModels (from robyn_outputs()) and OutputModels (from robyn_run()) are different and were being treated as equal. The following fix in the plots.R file allows both OutputModels to exist.
`if ("resultCollect" %in% names(OutputModels$trial1)) {
resultHypParam <- bind_rows(
lapply(OutputModels[
which(names(OutputModels) %in% paste0("trial", seq(OutputModels$trials)))
], function(x) x$resultCollect$resultHypParam)
)
} else {
resultHypParam <- bind_rows(OutputModels[
which(names(OutputModels) %in% paste0("trial", seq(OutputModels$trials)))
])
}
resultHypParam <- resultHypParam%>%
group_by(.data$trial) %>%
mutate(i = row_number()) %>% …
> fix: separate OutputCollect$OutputModels and OutputModels to produce ts_validation plot export #596

- R/R/inputs.R
Adjust the code so that it does not assume the column `ds` of the `dt_holidays` df is of type `datetime`, instead convert it using `as.Date`
Fixes #662
- fix: Bug fix (non-breaking change which fixes an issue)
- Was having issues running the process using `3.9.0`
- Forked the repo
- Updated the code and installed my own fork
- Ran it again and the error is gone
> Call as.Date on `floor_date` call

- R/R/refresh.R
The value of `plot_folder` is not being respected when calling `robyn_refresh` which results in the original folder being used by default (as described in #649). This PR adjust the code so that `plot_folder`'s value is respected when present.
Fixes #649
- fix: Bug fix (non-breaking change which fixes an issue)
> Respect plot_folder value on robyn_refresh

- R/DESCRIPTION
- R/R/inputs.R
- R/R/json.R
- **feat**: skip recreating InputCollect if provided on robyn_recreate()
- **fix**: added `organic_vars` to prophet decomposition
> feat and fix: InputCollect use case for robyn_recreate() + organic_vars added to prophet decomp

- website/yarn.lock
`yarn upgrade-interactive` and selected the docusaurus packages only. This obviously updated recursive dependencies too.
This seems to fix an issue with the mobile sidebar.
> Upgrade Docusaurus packages

- website/src/pages/index.js
This fixes warnings/errors that React is outputting.
1. `title` was an object, so the same `key` was being set for all elements. There's no need to use JSX for that since you're rendering an `<h3>` anyway, so easy win.
2. `<ul>` isn't a valid DOM child of `<p>` so rendering engines actually move DOM nodes around to make it work, which can break React. Use a `<div>` instead (and remove extra React fragment wrapping).
3. Properly case some attributes on `<iframe>`s
> Fix React warnings/errors.

- R/DESCRIPTION
- R/R/json.R
fix: compatibility with legacy files on robyn_recreate()
> fix: compatibility with legacy files on robyn_recreate()

- R/DESCRIPTION
- R/R/inputs.R
Issue with holidays data when monthly granularity fixed.
```
Error in mutate(., ds = cut(.data$ds, intervalType)) : 
ℹ In argument: `ds = cut(.data$ds, intervalType)`.
Caused by error in `cut.default()`:
! 'x' must be numeric
```
> fix: crashed cut() when monthly data

- R/DESCRIPTION
- R/R/checks.R
- R/R/inputs.R
When running `robyn_run()`, if a value contained "only negative values", it returned this error:
```
Error in { : 
task 1 failed - "arguments imply differing number of rows: 16, 17"
```
Fixed by checking on `robyn_input()` when all values from any column are negative (or zero) and transform it with `abs()`.
> fix: when all values on a column are negative crash

- R/DESCRIPTION
- R/R/convergence.R
- R/R/inputs.R
- R/R/plots.R
fix: winsorize errors with na.rm = TRUE #872
fix: InputCollect print when prophet is deactivated
> fix: winsorize errors with na.rm = TRUE #872 + InputCollect print when no prophet

- R/DESCRIPTION
- R/R/allocator.R
- R/R/auxiliary.R
- R/R/clusters.R
- R/R/inputs.R
- R/R/json.R
- R/R/plots.R
- R/man/robyn_outputs.Rd
- R/man/robyn_write.Rd
- demo/demo.R
- ~~docs: added commented examples in demo.R using `robyn_hypsbuilder()` and `robyn_modelselector()` functions to build hyperparameters default values and help on visual model selection based on combined metrics criteria (using lares >= 5.2.4 CRAN version)~~
- feat: enable `...` parameter to let users export additional information into .json files into a new "Extras" element using in `robyn_write()`
- feat: new `baseline_level` parameter for `robyn_onepagers()` to allow variables aggregations.
- fix: `check_metric_dates()` dynamic quiet on `robyn_allocator()` 
- fix: using `robyn_recreate()`, ask users to provide 'dt_input' input, and now mention that 'dt_holidays' input is optional
None of the changes or feats change default behaviors nor disrupt past versions.
> Bundle of small fixes and feats

- robyn_api/robynapi_enpoints.R
Update notebook and endpoint 
1. Notebook: updated index anchor #902
2. Notebook: updated how to run and stop API
3. Endpoint: fixed issue (InputCollect without setting context_vars and organic_vars) #906
- Fork the repo and create your branch from master (latest dev version).
- If you've changed docuemntation, run `devtools::document()`. Should update .Rd files.
- Ensure all tests pass, run `devtools::check()`. Should have no notes, no warning, no errors.
> Robyn api update notebook and endpoint

- R/DESCRIPTION
- R/R/clusters.R
- R/R/outputs.R
- R/man/robyn_clusters.Rd
- Fix: wrapped `pareto_clusters_detail.png` creation with try() to skip if too large + don't fail `robyn_outputs()` long runs
- Feat: new `max_clusters` param to avoid too many clusters. Default value set to 10
- Fix: warning saying Unknown or uninitialised column: nrmse_test
> fix: One or both dimensions exceed the maximum (50000px) error #874

- .gitignore
- python/src/robyn/__init__.py
- python/src/robyn/common/config/logging.conf
- python/src/robyn/data/validation/calibration_input_validation.py
- python/src/robyn/robyn.py
Added Python logger config.
1. robyn/common/config/logger.conf contains logger configuration. Currently it is set to print INFO for both file and console handler
2. log file will be created in current working directory of end usage. for example - log file will be created in tutorials directory if any tutorials is run. (not in working directory specified with instantiation of Robyn)
3. CalibrationInputValidation was broken and it was blocker to test logger changes so fixing it here as well.
> Adding python logger config

- .github/workflows/python-app.yml
- .gitignore
- python/src/robyn/data/validation/calibration_input_validation.py
- python/src/robyn/data/validation/mmmdata_validation.py
- python/src/robyn/robyn.py
- python/src/tests/test_mmmdata_validation.py
- python/tests/test_mmmdata_validation.py
Project Robyn
-------------
This commit implements several validation methods in the MMMDataValidation class within mmmdata_validation.py. These methods are Python equivalents of the validation checks performed in the R version of Robyn, specifically in the checks.R file.
The implemented methods include:
-   check_missing_and_infinite: Checks for missing (NA) and infinite values in the input data.
-   check_no_variance: Identifies columns with no variance in the input data.
-   check_date_variable: Validates the date variable in the input data.
-   check_dependent_variables: Ensures the dependent variables are valid and of the correct type.
These implementations aim to maintain parity with the R version while adapting to Python's syntax and pandas DataFrame operations.
Fixes # (issue …
> Implementation of some mmmdata_validation

- R/DESCRIPTION
- R/R/plots.R
To avoid white spaced and weird plots with spaces when channels impact changed to negative in some periods, migrating plot to columns instead of areas in `decomp_plot()`. Also, added ref line at zero.
See previous and new looks attached for reference. 
Complexity implementing: date is a continuous value; for columns to have no space between columns, they must be discrete. Solved.
> feat: cleaner decomp_plot() using cols instead of areas + ref line in 0

- python/src/robyn/data/entities/mmmdata.py
- python/src/robyn/modeling/pareto/hill_calculator.py
- python/src/robyn/modeling/pareto/pareto_optimizer.py
- python/src/robyn/modeling/pareto/pareto_utils.py
- python/src/robyn/modeling/pareto/response_curve.py
- python/src/tutorials/tutorial4_pareto.ipynb
- python/src/tutorials/utils/data_mapper.py
- python/tests/modeling_pareto/test_pareto_utils.py
##Pareto Optimizer Feature without the data optimizer
Updated data mapper to map outputmodel from R to python
Calculates pareto front
This PR adds the logic that rewrite response.R based on the call from Pareto_optimizer
It also Calculates the hill hyperparameters from the response results.
Tested using test data from the `robyn_python_notebook.ipynb` before it calls robyn_output api endpoint.
Generated this new notebook to test the python logic
> Updating pareto-optimizer until it generates plot data

- python/src/robyn/visualization/transformation_visualizer.py
Add spend vs effect share comparison plot
Implements dual-axis visualization comparing spend and effect shares
Matches R implementation with:
Stacked bar chart for spend/effect percentages
Secondary axis for performance metrics
Proper color schemes and formatting
Supports both standalone and subplot integration
Handles automatic scaling and layout
Testing:
Graph plot by R code
> Robyn one pager: generate_spend_effect_comparison plot implementation

- python/src/robyn/visualization/response_visualizer.py
Add response curves visualization
Implement response curves showing spend vs response relationship
Add carryover effect shading for each channel
Display mean spend points with formatted labels
Support both standalone and subplot integration
Use abbreviated axis labels for large numbers
Add legend with channel colors
Include proper grid and axis styling
Testing:
Graph plotted by R code
> Robyn one pager: Response curve plot implementation

- python/src/robyn/reporting/onepager_reporting.py
- python/src/robyn/robyn.py
- python/src/robyn/tutorials/tutorial1.ipynb
Fix end-to-end one pager generation flow
* Remove redundant parameter passing
* Fix method call in plot_one_pager
- Update type hints and parameters
* Change List[str] to List[PlotType] for plots parameter
* Update ClusteringConfig to ClusteredResult
* Add proper return type hints
- Improve error handling
* Add better logging messages
* Add proper figure return handling
Add single solution selection option
- Allow passing specific solution_id to plot_one_pager
* Maintain default top pareto behavior
* Update documentation with usage examples"
Testing: Verified one pager generation from Robyn class works end-to-end"
> Robyn one pager end to end flow for tutorial 1

- python/src/robyn/modeling/ridge/ridge_metrics_calculator.py
- python/src/robyn/tutorials/tutorial1.ipynb
- python/src/robyn/tutorials/tutorial4_pareto.ipynb
- Added absolute value calculation for effect: effect = np.abs(coef * spend)
- Using absolute values for non-zero effect calculation: non_zero_effect = np.abs(X[col][non_zero_mask] * coef)
- Effect shares are now calculated using these absolute effects
> [accuracy] modeling changes for calculate_decomp_spend_dist

- R/DESCRIPTION
- R/R/plots.R
- R/R/transformation.R
- R/man/Robyn.Rd
Fixing the following warning everytime a one-pager is created:
```
Warning in geom_text(aes(x = max(.data$x), y = 0.5, vjust = -0.5, hjust = 1, :
All aesthetics have length 1, but the data has 250 rows.
ℹ Please consider using annotate() or provide this layer with data containing a single row.
```
The warning message is due to the fact that geom_text is trying to apply the same label ("Halflife") across multiple rows of the data, which causes a mismatch in the number of aesthetics.
> fix: adstock plot warning on changing geom_text() to annotate()

- R/DESCRIPTION
- R/R/allocator.R
- R/R/auxiliary.R
- R/R/checks.R
- R/R/model.R
- R/R/plots.R
Improve modeling window coverage accuracy by considering all real dates in the data. With this change:
1. When window_end is not defined, the default is now the latest available day before the next logical date in the data. 
2. Allows for days larger than the max but smaller than the next logical date without a warning.
The results are exactly the same, it's a matter of "correct" coverage. For monthly data, if modeling window covers from "2024-01-01" to "2024-12-31", the data for last month is "2024-12-01" but it actually covers until "2024-12-31".
This logic is triggered only when window_end is not provided.
---
Also, fixed issue with legacy InputCollect and budget allocator using paid_media_selected (similar to #1194)
> fix: modeling window coverage considers all actual dates data + legacy InputCollect for BA bug

- python/pyproject.toml
- python/requirements.txt
Looking at the `pyproject.toml` and `requirements.txt` files, `nevergrad` is listed twice as a dependency. This PR removes the duplicate dependency from both files. This should only be a cosmetic change.
- remove duplicate nevergrad from requirements.txt for robynpy
- remove duplicate nevergrad from pyproject.toml for robynpy
> Remove duplicate nevergrad dependency

- python/src/robyn/modeling/ridge/ridge_data_builder.py
- python/tests/unit/modeling/ridge/test_adstock.py
This PR optimizes `_geometric_adstock`, the main performance bottleneck, reducing its execution time by **~99%** and improving the **total model train time by ~40%** on Python version.
This PR does not address an existing GitHub issue but significantly improves performance.
- **fix**: Performance optimization (non-breaking change that improves efficiency)
- **test**: Added unit test to validate correctness  
- `_geometric_adstock` previously accounted for **39% of the total model train time**, significantly slowing down model execution.  
- This function was rewritten using `scipy.signal.lfilter`, replacing a Python loop with a **highly efficient SciPy-based implementation (built on NumPy)**.  
- This change **improves execution time from 108.9s → 0.495s** (~99% speedup), leading to an …
> Optimize _geometric_adstock for 99% function speedup, reducing total model train time by ~40% - Python version
